### ISSUE TITLE
Loading of scenarios and courses is very slow

### ISSUE THREAD

**Issue by ebauman** [hobbyfarm/hobbyfarm#113]
**What happened**: Courses and scenarios take a long time to list. This is evident on both a local instance of HF as well as production. 

**What you expected to happen**: Courses and scenarios should list very quickly for end users. The list of content available to them should be almost immediately available. 

**How to reproduce it (as minimally and precisely as possible)**: Use Rancher v0.2.0+

**Comment by ebauman** [comment]
Seems to be occurring in situations where there are large number of invalid access codes on the user.

**Comment by ebartz** [comment]
I think this happens because gargantua keeps querying etcd multiple times which seems to cause performance issues in etcd and also very high CPU usage on the gargantua pod. This also seems to happen if you have many vmclaims.

Our current workaround is to clean unused resources or even reinstall the k8s cluster so that we don't have to wait for unfinished resources or clean up resources manually.

On one hand it is pretty awesome that all the application related state resides in etcd - on the other hand that means we totally depend on the kubernetes api and etcd to be available. Also querying etcd so much for checking on updates of resources causes unnecessary high load in gargantua and etcd.

I think introducing redis could solve such issues. Instead of polling for updates, this could be redesigned to be a pub/sub architecture.
